// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./components/Application/Application.vue')['default']
    CarbonMoon: typeof import('./components/icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./components/icon/CarbonSettings.vue')['default']
    DefaultSetting: typeof import('./layout/src/components/drawer/defaultSetting.vue')['default']
    DialogContent: typeof import('./components/DialogContent/index.vue')['default']
    Drawer: typeof import('./layout/src/components/drawer/index.vue')['default']
    Footer: typeof import('./layout/src/components/Footer/index.vue')['default']
    IcBaselineWbSunny: typeof import('./components/icon/IcBaselineWbSunny.vue')['default']
    LoadingContent: typeof import('./components/LoadingContent/index.vue')['default']
    MessageContent: typeof import('./components/MessageContent/index.vue')['default']
    Moon: typeof import('./components/icon/moon.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NetFix: typeof import('./components/icon/NetFix.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotFound: typeof import('./components/not-found/not-found.vue')['default']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Src: typeof import('./layout/src/index.vue')['default']
  }
}

export { }
